when:
  - event: pull_request
  - event: push
    branch: main

steps:
  format:
    image: golang:1.26-trixie
    environment:
      GOEXPERIMENT: jsonv2
    commands:
      - uname -m
      - if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
