when:
  - event: pull_request
  - event: push
    branch: main

steps:
  lint:
    image: golang:1.26-trixie
    environment:
      GOEXPERIMENT: jsonv2
    commands:
      - uname -m
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.10.1
      - golangci-lint run ./...
