labels:
  platform: linux/amd64

when:
  - event: pull_request
  - event: push
    branch: main

services:
  - name: postgresql
    image: postgres:18-trixie
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: minhareceita
      POSTGRES_USER: minhareceita
      POSTGRES_DB: minhareceita
  - name: mongodb
    image: rnsc/mongo-wo-avx:8.0.26
    ports:
      - 27017

steps:
  test:
    image: golang:1.26-trixie
    environment:
      GOEXPERIMENT: jsonv2
      TEST_POSTGRES_URL: postgres://minhareceita:minhareceita@postgresql:5432/minhareceita?sslmode=disable
      TEST_MONGODB_URL: mongodb://mongodb:27017/minhareceita
    commands:
      - go test --race ./...
